"""De-biasing check for the fusion model (answer to the weak-label circularity critique).

The fusion model concatenates 26 linguistic + 7 SHAI features that are computed
from the SAME lexicons that build the weak labels, so its IN-DOMAIN gains are
partly circular. This experiment isolates the encoder gain from the label's
vocabulary by re-running the winning fusion+focal model with the label-lexicon
features removed, and reports the EXTERNAL transfer (RMHD + expert-labelled
ANGST) as the headline — ANGST being the only ground truth not generated by this
project's heuristics.

Variants (all trained on the same author-disjoint split, identical seed):
  baseline            plain multitask (no fusion, no focal)
  fusion_focal_all    fusion+focal, all 33 features (the original, partly circular)
  fusion_focal_nolex  fusion+focal, label-lexicon term/phrase rates + SHAI removed
  fusion_focal_style  fusion+focal, ALL clinical vocabulary removed (style/structure only)

If the no-lexicon / style-only variants still beat the baseline on ANGST, the
fusion gain is real signal, not the model reading its own label vocabulary.

GPU. Run:
  python scripts/exp_fusion_debias.py
  python scripts/exp_fusion_debias.py --variants baseline,fusion_focal_nolex --max-train 60000 --epochs 3
"""
from __future__ import annotations

import argparse
import gc
import os
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GroupShuffleSplit

from src.evaluation.external import load_angst, load_rmhd
from src.evaluation.metrics import full_report
from src.models.registry import build_model
from src.utils.config import load_model_config
from src.utils.io import read_parquet

DATA = "data/processed/labeled.parquet"
RMHD_DIR = "data/external/rmhd"
ANGST_DIR = "data/external/angst"
SEED = 42
TARGETS = ["anxiety", "health_anxiety", "depression", "suicidality"]
POS_SUBS = ["anxiety", "healthanxiety", "socialanxiety"]
NEG_SUBS = ["fitness", "parenting", "meditation", "conspiracy"]
OUTCSV = Path("experiments/fusion_debias.csv")
DOC = Path("docs/fusion_debias.md")
FIG = Path("docs/figures/fusion_debias.png")

_FOCAL = {"enabled": True, "gamma": 2.0}
VARIANTS = {
    "baseline":           {"fusion": {"enabled": False}, "focal": {"enabled": False}},
    "fusion_focal_all":   {"fusion": {"enabled": True, "feature_set": "all"}, "focal": dict(_FOCAL)},
    "fusion_focal_nolex": {"fusion": {"enabled": True, "feature_set": "no_label_lexicon"}, "focal": dict(_FOCAL)},
    "fusion_focal_style": {"fusion": {"enabled": True, "feature_set": "style_only"}, "focal": dict(_FOCAL)},
}


def _cap(df, n):
    return df.sample(n=n, random_state=SEED).reset_index(drop=True) if n and len(df) > n else df


def _external_auroc(predict, df, ti):
    if df is None or df.empty:
        return None
    scores = np.asarray(predict(df))[:, ti]
    return round(float(roc_auc_score(df["y"].to_numpy(), scores)), 4)


def _free_gpu():
    gc.collect()
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:  # noqa: BLE001
        pass


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variants", default=",".join(VARIANTS))
    ap.add_argument("--max-train", type=int, default=60000)
    ap.add_argument("--max-eval", type=int, default=20000)
    ap.add_argument("--epochs", type=int, default=3)
    args = ap.parse_args()
    chosen = [v.strip() for v in args.variants.split(",") if v.strip() in VARIANTS]

    df = read_parquet(DATA)
    df = df[(df["clean_text"].astype(str).str.len() >= 30) & df["author_hash"].notna()].reset_index(drop=True)
    tr, te = next(GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED).split(df, groups=df["author_hash"].values))
    train = _cap(df.iloc[tr].reset_index(drop=True), args.max_train)
    test = _cap(df.iloc[te].reset_index(drop=True), args.max_eval)
    print(f"author-disjoint: train={len(train):,} test={len(test):,}", flush=True)

    rmhd = load_rmhd(RMHD_DIR, POS_SUBS, NEG_SUBS, cap_per_sub=5000, seed=SEED)
    try:
        angst = load_angst(ANGST_DIR, target="anxiety")
    except Exception as ex:  # noqa: BLE001
        print(f"  (ANGST unavailable: {ex})", flush=True)
        angst = None
    ti = TARGETS.index("anxiety")
    if angst is None:
        print("  WARNING: ANGST not loaded — the headline (bias-free) metric will be missing.", flush=True)

    rows: list[dict] = []
    for vi, name in enumerate(chosen, 1):
        cfg = load_model_config("configs/models/fusion_multitask.yaml")
        for k, v in VARIANTS[name].items():
            cfg.extra[k] = v
        cfg.extra.setdefault("train", {})["num_train_epochs"] = args.epochs
        nfeat = {"all": 33, "no_label_lexicon": 19, "style_only": 18}.get(
            VARIANTS[name]["fusion"].get("feature_set"), 0) if VARIANTS[name]["fusion"].get("enabled") else 0
        print(f"\n=== [{vi}/{len(chosen)}] {name}  (fused features: {nfeat}) ===", flush=True)
        model = build_model(cfg).fit(train, val=None)
        proba = np.asarray(model.predict_proba(test))
        row = {"variant": name, "n_fused_feats": nfeat}
        for i, t in enumerate(TARGETS):
            y = (test[f"label_{t}"].astype(float).fillna(0) >= 0.5).astype(int).to_numpy()
            if y.sum() < 5 or (y == 0).sum() < 5:
                continue
            row[f"{t}_f1"] = round(full_report(y, proba[:, i], bootstrap=False)["f1"], 4)
        row["rmhd_auroc"] = _external_auroc(model.predict_proba, rmhd if not rmhd.empty else None, ti)
        row["angst_auroc"] = _external_auroc(model.predict_proba, angst, ti)
        rows.append(row)
        pd.DataFrame(rows).to_csv(OUTCSV, index=False)
        print(f"  {name}: anxiety_f1={row.get('anxiety_f1')} health_f1={row.get('health_anxiety_f1')} "
              f"suic_f1={row.get('suicidality_f1')} | RMHD={row['rmhd_auroc']} ANGST={row['angst_auroc']}", flush=True)
        del model
        _free_gpu()

    out = pd.DataFrame(rows)
    OUTCSV.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(OUTCSV, index=False)

    # headline figure: external transfer (RMHD + ANGST) per variant, with baseline reference lines
    base = out[out["variant"] == "baseline"]
    base_rmhd = float(base["rmhd_auroc"].iloc[0]) if not base.empty and base["rmhd_auroc"].notna().any() else None
    base_angst = float(base["angst_auroc"].iloc[0]) if not base.empty and base["angst_auroc"].notna().any() else None
    fig, ax = plt.subplots(figsize=(10, 5.5))
    x = np.arange(len(out)); w = 0.38
    ax.bar(x - w / 2, out["rmhd_auroc"], w, label="RMHD AUROC (subreddit-proxy)", color="#8C8C8C")
    ax.bar(x + w / 2, out["angst_auroc"], w, label="ANGST AUROC (expert, bias-free)", color="#2CA02C")
    if base_rmhd:
        ax.axhline(base_rmhd, ls=":", color="#8C8C8C", lw=1)
    if base_angst:
        ax.axhline(base_angst, ls="--", color="#2CA02C", lw=1, label="baseline ANGST")
    for i, (r, a) in enumerate(zip(out["rmhd_auroc"], out["angst_auroc"])):
        if pd.notna(r): ax.text(i - w / 2, r + 0.003, f"{r:.3f}", ha="center", fontsize=8)
        if pd.notna(a): ax.text(i + w / 2, a + 0.003, f"{a:.3f}", ha="center", fontsize=8)
    ax.set_xticks(x); ax.set_xticklabels(out["variant"], rotation=20, ha="right", fontsize=8)
    ax.set_ylabel("zero-shot transfer AUROC"); ax.set_ylim(0.5, 1.0)
    ax.set_title("De-biasing the fusion model: external transfer when label-vocabulary features are removed")
    ax.legend(fontsize=8)
    fig.tight_layout(); FIG.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG, dpi=130); plt.close(fig)

    cols = ["variant", "n_fused_feats", "anxiety_f1", "health_anxiety_f1", "suicidality_f1", "rmhd_auroc", "angst_auroc"]
    cols = [c for c in cols if c in out.columns]
    md = [
        "# De-biasing the fusion model (weak-label circularity check)",
        "",
        "The fusion model's clinical features are computed from the same lexicons that build the weak "
        "labels, so its in-domain gains are partly circular. Here the winning `fusion+focal` model is re-run "
        "with the label-vocabulary features removed, and the headline is the EXTERNAL transfer — RMHD "
        "(subreddit-proxy) and **ANGST (expert psychologists, the only bias-free ground truth)**. "
        "`scripts/exp_fusion_debias.py`. Same author-disjoint split for all variants.",
        "",
        "- `all` = 33 features · `no_label_lexicon` = 19 (drops 7 label term/phrase rates + 7 SHAI) · "
        "`style_only` = 18 (also drops the somatic body-part lexicon).",
        "",
        "_Regenerate: `python scripts/exp_fusion_debias.py`_",
        "",
        "| " + " | ".join(cols) + " |",
        "|" + "|".join(["---"] * len(cols)) + "|",
    ]
    for r in rows:
        md.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    md += [
        "", "![fusion debias](figures/fusion_debias.png)", "",
        "## How to read this",
        "",
        "- Compare the fusion variants to **baseline on ANGST** (expert labels — the only ground truth the "
        "weak labels cannot contaminate). If the no-lexicon / style-only variants do not clearly beat "
        "baseline on ANGST, the fusion gain is not a robust, non-circular benefit.",
        "- Watch the in-domain rare-class F1 (suicidality, health anxiety): if a lift under `all` disappears "
        "under `no_label_lexicon`, that lift was circular — driven by features computed from the same lexicon "
        "as the label.",
        "- Differences of a few hundredths are within single-seed noise; multi-seed averaging is needed before "
        "any architectural claim.",
    ]
    DOC.write_text("\n".join(md), encoding="utf-8")

    print("\n", out.to_string(index=False))
    print(f"\nWrote {OUTCSV}, {DOC}, {FIG}")


if __name__ == "__main__":
    main()
